[supervisord]
nodaemon=true

[program:octane]
command=sh -c "php artisan octane:stop || true && php artisan octane:start --server=swoole --host=0.0.0.0 --port=80"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/octane.err.log
stdout_logfile=/var/log/octane.out.log

[program:websocket]
command=php /app/bootstrap/websocket.php
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/websocket.err.log
stdout_logfile=/var/log/websocket.out.log
